language: minimal

services:
  - docker

stages:
  - build

jobs:
  include:
  - stage: build
    script:
      - echo "Stage [build] - Step [script] ..."
      - docker build --no-cache --pull --build-arg ELASTICMS_VERSION_ARG=$ELASTICMS_VERSION --build-arg ELASTICMS_DOCKER_RELEASE_ARG=$ELASTICMS_DOCKER_RELEASE --build-arg VCS_REF_ARG=$VCS_REF --build-arg BUILD_DATE_ARG=$BUILD_DATE -t docker.io/$DOCKER_USERNAME/elasticms-web:RC -f box-web/Dockerfile .
      - docker build --no-cache --pull --build-arg ELASTICMS_VERSION_ARG=$ELASTICMS_VERSION --build-arg ELASTICMS_DOCKER_RELEASE_ARG=$ELASTICMS_DOCKER_RELEASE --build-arg VCS_REF_ARG=$VCS_REF --build-arg BUILD_DATE_ARG=$BUILD_DATE -t docker.io/$DOCKER_USERNAME/elasticms-php:RC -f box-php/Dockerfile .
    after_script:
      - echo "Stage [Build] - Step [after_script] ..."
      - docker images
    after_success:
      - echo "Stage [Build] - Step [after_success] ..."
      - docker login -u="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
      - docker tag docker.io/$DOCKER_USERNAME/elasticms-web:RC docker.io/$DOCKER_USERNAME/elasticms-web:$ELASTICMS_DOCKER_TAG
      - docker tag docker.io/$DOCKER_USERNAME/elasticms-php:RC docker.io/$DOCKER_USERNAME/elasticms-php:$ELASTICMS_DOCKER_TAG
      - docker tag docker.io/$DOCKER_USERNAME/elasticms-web:RC docker.io/$DOCKER_USERNAME/elasticms-web:$ELASTICMS_VERSION
      - docker tag docker.io/$DOCKER_USERNAME/elasticms-php:RC docker.io/$DOCKER_USERNAME/elasticms-php:$ELASTICMS_VERSION
      - docker tag docker.io/$DOCKER_USERNAME/elasticms-web:RC docker.io/$DOCKER_USERNAME/elasticms-web:latest
      - docker tag docker.io/$DOCKER_USERNAME/elasticms-php:RC docker.io/$DOCKER_USERNAME/elasticms-php:latest
      - docker push docker.io/$DOCKER_USERNAME/elasticms-web:$ELASTICMS_DOCKER_TAG
      - docker push docker.io/$DOCKER_USERNAME/elasticms-php:$ELASTICMS_DOCKER_TAG
      - docker push docker.io/$DOCKER_USERNAME/elasticms-web:$ELASTICMS_VERSION
      - docker push docker.io/$DOCKER_USERNAME/elasticms-php:$ELASTICMS_VERSION
      - docker push docker.io/$DOCKER_USERNAME/elasticms-web:latest
      - docker push docker.io/$DOCKER_USERNAME/elasticms-php:latest

env:
  global:
  - ELASTICMS_VERSION=1.9.55
  - ELASTICMS_DOCKER_RELEASE=1
  - ELASTICMS_DOCKER_TAG="$ELASTICMS_VERSION-$ELASTICMS_DOCKER_RELEASE"
  - VCS_REF=${TRAVIS_COMMIT}
  - BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
