sudo: required
language: php
php:
- '7.1'
services:
- docker
stages:
- build
- aws-deploy
jobs:
  include:
  - stage: build
    script:
    - echo "Stage [build] - Step [script] ..."
    - git remote add -f elasticms git@github.com:ems-project/elasticms.git
    - git merge -s ours --no-commit --allow-unrelated-histories elasticms/master
    - git read-tree --prefix=src/ -u elasticms/master
    - git commit -m "Subtree elasticms/master merged in src"
    - composer -v install --no-interaction -d src/
    - docker build --no-cache --pull -t docker.io/$DOCKER_USERNAME/elasticms-web:latest -f box-web/Dockerfile .
    - docker build --no-cache --pull -t docker.io/$DOCKER_USERNAME/elasticms-php:latest -f box-php/Dockerfile .
    after_script:
    - echo "Stage [Build] - Step [after_script] ..."
    - docker images
    after_success:
    - echo "Stage [Build] - Step [after_success] ..."
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $DOCKER_USERNAME/elasticms-web:latest
    - docker push $DOCKER_USERNAME/elasticms-php:latest
  - stage: aws-deploy
    script:
    - echo "Stage [aws-deploy] - Step [script] ..."
    deploy:
      provider: script
      script: bash .aws/deploy.sh
      on:
        branch: master
env:
  global:
  - secure: g2TUP6ISSP6DMI7d3vVBC1iG6F+o2epySo+Yc/nAALbs5Raelpoosm4bWuyO6Uqtp+yIaF5zYOilHface3N4yOWVzaqr2PaNzXZ+KvCxqePDNVkLunu6ZjlrEHzjk5CMvyW4FCPXhhqXP42NftdTqP+cptZq3P5iAbI06d8060/Dx9NhftVPsrW4Fy2rUTPhObAY2QWYt6ogTqLF/l5c+qHwj4FButQ8fMFhMntvv6RQRqchNHg1ahz3HaInRnieCxOn3QJZxnJjWWVO3HccPY8FRsOverXRBFcFd2KoXbZHUo7FUnkrBhl7WgoDjOel5tXALdV4wDPMvwE72b46PWMondTwU5+MuGRDgkMkqkRjkaO0kKDALg3/r/vay/S0GHfkE7U1RIe8vSozTSeQv4JMunI190Kc7v0xK1EiWy8iXSOTJOkstdi/IyH2aYe41oCkV83n+W38MMGSyfTR57xW05fNyNGGE+StO+h0JaXq8ZD61G0gj+IykV7SS3UF4KnsXBDexHQOOyJoOcRnTiR8X0FcU5PwJFCie5Y7jvb3YoRDGf2aHEk2N5EohRo/sYmrBe7VgiQVVWiPl9ljXZrEdkIzR/SZZXQgRgmZcbDNIC+33yWOE27l+O5FDz5idbjdk0XugkP9dPCJPmgpr5GiFG8chvHAyxR3tVkIRGk=
  - secure: IUVXHkxuxCpWhvNQYVUjp6oZPU1twChL419ri7+bmQXgw2N5OWIaPYvhKaPt3Oe62z/+zzl7gt9dQL3QDJtgoMzeenTHZtsiqaHdTVKtQ7Cbl6WQF+EMKa9R3GPOaQk2KUr+pC/x72p4bDAYmDRuRMjF86hR7MwdvaU0IOMOX/wgls9rJrngyto+doocFw8kXRWmT6KCMA6RqXHkhfvLEr1ZjQe1PMNiyUrhdV9NUMCO/Pym1gHwxQpAN3nkLlbv8zEaDB2faeuHaW4w0dcc/UUEfN9W8V3Wp9872q4+JDgIE1FlNkA9y37ICeIWpE9FnjCM/W3JWGx8MKuvK7O0GxcLj7PP+W0Q3ttEnezzDCBhc2o2XSo77LZZkO1jY4vF1RHC5eq4/EXLObXaL8SVgWUl6NNWP4bXQ9Tp4HfUwx3TK18tgQqIrytX2htMNLiAtV4i0dT/R6NzuUCG7csLVdZmtmoHxqfUtgt9yVNvCAD3cR7AEdqvxZHP1MU036ykFhbw+cd1BE22E6pSL/0YdV7jzFV4ZMp0PEyZYNEy8arizdhFAm00Wre/OMhOgQ0OPUeCb1HAscaTA1LmA/zj0p6hd1wjVm4hw9011Aj4lB6dsuPX6FPwFgn7dCmdKhFUFxAPcxLubCJFNHy45wnRasqzvGTc1gPCEgHjTCCDyO0=
