app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
ems_core:
    resource: "@EMSCoreBundle/Controller/"
    type:     annotation
#    prefix:   /admin
ems_local_user:
    resource: "@EMSLocalUserBundle/Controller/"
    type:     annotation